---
title: "Projected novelty in the climate envelope of the California Current at multiple spatial-temporal scales"
date: 2022-04-04
categories: 
  - Ocean Physics and Biogeochemistry
pub-info:
  reference: >-
    Smith, J. A., Pozo Buil, M., Fiechter, J., Tommasi, D., & Jacox, M. G. (2022). Projected novelty in the climate envelope of the California Current at multiple spatial-temporal scales. <em>PLoS Climate</em>, 1(4), e0000022. doi: <a href="https://doi.org/10.1371/journal.pclm.0000022">https://doi.org/10.1371/journal.pclm.0000022</a>
  links:
    - name: PDF
      url: Smith_PlosClimate_2022.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.1371/journal.pclm.0000022
      icon: fa-solid fa-scroll
---

## Abstract

A useful measure of general climate stress is where and when novel habitats emerge. Here we evaluate ‘climate envelope novelty’–a spatial indicator of system-level habitat change–in the California Current System (CCS), by quantifying the emergence of novel ocean conditions in multivariate physical-biogeochemical space. We use downscaled climate projections from three earth system models out to 2100 under emission scenario RCP8.5, and detect novelty at multiple spatial-temporal scales using two methods (n-dimensional hypervolumes and extrapolation detection). Under high emissions, persistent novelty doesn’t appear until around 2040 and then only in small patches of Southern California and the Pacific North West. However, novelty increases rapidly after this (especially in warmer seasons), so that by 2060 up to 50% of the CCS in an average year has shifted to a novel local climate, which increases to 100% by 2090. These results are for the average year, and the first years to experience these levels of novelty typically occur 20 years sooner. The ecosystem will increasingly experience novel combinations of warmer temperatures, lower dissolved oxygen (especially inshore), and a shallower mixed layer (especially offshore). The emergence of extensive local novelty year-round has implications for the required ubiquitous redistribution or adaptation of CCS ecology, and the emergence of extensive regional novelty in warmer months has implications for bioregional change and regionally emerging fisheries. One of our climate projections showed considerably less novelty, indicating that realistic uncertainties in climate change (especially the rate of warming) can mean the difference between a mostly novel or mostly analog future.