---
title: "Report from the Future Seas stakeholder engagement workshop, November 2022"
date: 2023-09-21
categories: 
  - Climate and Fisheries
  - Ocean Physics and Biogeochemistry
  - Species Distribution Modeling and Dynamic Ocean Management
  - Coupled Mechanistic Modeling
  - Ocean Observing
pub-info:
  reference: >-
    Quezada, F., Wildermuth, R., Tommasi, D., Kaplan, I., Muhling, B., Stohs, S., Frawley, T., Hernvann, P.-Y., Koenigstein, S., & Kuriyama, P. (2023). Report from the Future Seas stakeholder engagement workshop, November 2022.
  links:
    - name: PDF
      url: FS_stakeholder_workshop_2022-2.pdf
      icon: fa-solid fa-file-pdf
      local: true
---

## Abstract

A 2-day virtual stakeholder engagement workshop in support of the NOAA-funded Future Seas
project was held November 28 and 29, 2022. Attendees included academic and government
scientists as well as representatives of the National Marine Fisheries Service West Coast Region,
the Southwest Fisheries Science Center, the Pacific Fishery Management Council, state agencies
(California, Oregon, and Washington Departments of Fish and Wildlife), the Quinault Indian
Nation, CPS (coastal pelagic species) fishermen, and CPS processors. The workshop began with
an overview of the Future Seas project, including project aims for the recent phase 2 of the project,
and a summary of the results obtained from phase 1. The rest of day 1 was dedicated to the socio-
economic part of the project, while day 2 focused on the Management Strategy Evaluation (MSE).
The discussion was lively and productive and is detailed in this report. With input from all
represented stakeholders, the Future Seas team was able to synthesize for the CPS fishery the
observed target species dynamics, the key drivers that affect fishing operations, species portfolio
and switching behavior, harvest location, port landings decisions and “no fishing” decisions, and
key climate vulnerabilities, management strategies and performance metrics. These findings will
guide the development and execution of the models elaborated for the project and ensure that they
address the concerns and ideas of stakeholders. Attendees expressed appreciation for being
considered in the modeling design and have interest in follow-up meetings with the researchers of
the project as needed.