---
title: "Changes to the structure and function of an albacore fishery reveal shifting social-ecological realities for Pacific Northwest fishermen"
date: 2021-03-01
categories: 
  - Human Dimensions of Fisheries
pub-info:
  reference: >-
    Frawley, T. H., Muhling, B. A., Brodie, S., Fisher, M. C., Tommasi, D., Le Fol, G., Hazen, E. L., Stohs, S. S., Finkbeiner, E. M., & Jacox, M. G. (2021). Changes to the structure and function of an albacore fishery reveal shifting social-ecological realities for Pacific Northwest fishermen. <em>Fish ansd Fisheries</em>, 22, 280-297. doi: <a href="https://doi.org/10.1111/faf.12519">https://doi.org/10.1111/faf.12519</a> 
  links:
    - name: PDF
      url: Frawley_FF_2021.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.1111/faf.12519
      icon: fa-solid fa-scroll
---

## Abstract

Marine fisheries around the globe are increasingly exposed to external drivers of social and ecological change. Though diversification and flexibility have historically helped marine resource users negotiate risk and adversity, much of modern fisheries management treats fishermen as specialists using specific gear types to target specific species. Here, we describe the evolution of harvest portfolios amongst Pacific Northwest fishermen over 35+ years with explicit attention to changes in the structure and function of the albacore (*Thunnus alalunga*, Scombridae) troll and pole-and-line fishery. Our analysis indicates that recent social–ecological changes have had heterogenous impacts upon the livelihood strategies favoured by different segments of regional fishing fleets. As ecological change and regulatory reform have restricted access to a number of fisheries, many of the regional small (<45 ft) and medium (45–60 ft) boat fishermen who continue to pursue diverse livelihood strategies have increasingly relied upon the ability to opportunistically target albacore in coastal waters while retaining more of the value generated by such catch. In contrast, large vessels (>60 ft) targeting albacore are more specialized now than previously observed, even as participation in multiple fisheries has become increasingly common for this size class. In describing divergent trajectories associated with the albacore fishery, one of the US West Coast's last open-access fisheries, we highlight the diverse strategies and mechanisms utilized to sustain fisheries livelihoods in the modern era while arguing that alternative approaches to management and licensing may be required to maintain the viability of small-scale fishing operations worldwide moving forward.