---
title: ""
toc: false
---

:::: {.column-page}

## Coastal Pelagic Species

::: columns
::: {.column width="60%"}
Forage species, such as sardine, anchovy, and squid, serve a critical
ecological function in the California Current as a link between the
planktonic food web and higher trophic levels. Forage species also
support important direct commercial fisheries. The fleet targeting
forage species is referred to as the coastal pelagic species (CPS) fleet
and composition of its portfolio varies regionally and over time given
spatio-temporal variability in forage species composition across the
U.S. West Coast as well as market forces. The fishery is the largest,
and most diverse in California, with the main target species being
market squid, Pacific sardine, mackerels and Northern anchovy. Of these,
market squid is the most lucrative, and generates the most revenue. By
contrast, the CPS fleet in Oregon and Washington has largely been
dependent on Pacific sardine. In 2018 CPS accounted for 22% of total
west coast landings by weight, and generated \$82 million in ex-vessel
revenue. In California, the CPS fishery contributed to 71% of 2018 total
state landings. Key issues for this fishery include stabilizing catch
from year to year, promoting efficiency and profitability given the high
environmentally-driven temporal variability in species availability and
portfolio composition, and maintaining adequate forage for predators.
:::

::: {.column width="40%"}
![Pacific sardine<br>(*Sardinops
sagax*)](images/Sardinops_sagax.jpg.webp){style="fig-align:center; max-width:400px"}
:::
:::

## Albacore Tuna

::: columns
::: {.column width="40%"}
![Albacore tuna<br>(*Thunnus
alalunga*)](images/albacore_white_background-e1595276693649.jpeg.webp){width=400px}
:::

::: {.column width="60%"}
The U.S. west coast commercial albacore fishery operates primarily out
of Pacific Northwest ports in Oregon and Washington, using surface gear
(hook-and-line and troll). The albacore fishery is economically valuable
in all three west coast states; in 2015, hook-and-line vessels landed
11,255 metric tons of albacore to west coast ports, generating \$29.3
million in ex-vessel revenue. Of particular interest for management are
climate-driven distribution shifts of albacore (for example, in a warmer
ocean albacore will likely move to more northern waters along the U.S.
and Canadian west coasts) and the role of the albacore fishery, which is
not limited entry, as “insurance” when other fisheries are not
profitable.
:::
:::


## Swordfish

::: columns
::: {.column width="60%"}
The California Drift Gillnet fishery is a limited entry fishery that
primarily targets broadbill swordfish in federal waters off California.
In 2015, Drift Gillnet vessels landed 66 metric tons of swordfish,
generating \$454,000 in ex-vessel revenue. Due to documented bycatch of
protected marine species including marine mammals and sea turtles,
large-scale closures have been enacted to reduce interactions between
fishers and bycatch species. These closures have resulted in lost
opportunity and reduced profitability for fishers. To reduce opportunity
cost to fishers while protecting bycatch species, we are exploring
alternative management scenarios in which closures are enacted
dynamically based on the likelihood that individual species are present
in a given area.
:::

::: {.column width="40%"}
![Swordfish<br>(*Xiphias
gladius*)](images/swordfish_white_background-e1595276667337.jpeg.webp){width=400px}
:::
:::

::::

