---
title: ""
format: 
  html:
    page-layout: full
toc: false
---

<div class="hero"></div>

### Future Seas is a collaborative, interdisciplinary effort to explore potential impacts of climate change on U.S. west coast fisheries and to evaluate strategies for managing those impacts.

<br>

<center>
<span style="color:darkblue; font-size:2rem">Learn more:</span>
</center>

:::: {.grid}

::: {.card .g-col-4}
<center><span style="font-size:1.5rem"><a href="fisheries.qmd" class="stretched-link">{{< fa ship >}}**Fisheries**</a></span></center>
<br>
We are focused on the swordfish, albacore tuna, and coastal pelagic fisheries off the U.S. west coast, each of which involves a unique set of ecological and socioeconomic concerns.
:::

::: {.card .g-col-4}
<center><span style="font-size:1.5rem"><a href="Science/index.qmd" class="stretched-link">{{< fa chart-bar >}}**Science**</a></span></center>
<br>
Dynamical, statistical, and conceptual models are being combined in a framework to project physical, ecological, and socioeconomic change and to evaluate uncertainty in the models.
:::

::: {.card .g-col-4}
<center><span style="font-size:1.5rem"><a href="Team/index.qmd" class="stretched-link">{{< fa users >}}**Our Team**</a></span></center>
<br>
We are climate scientists, oceanographers, ecologists, economists, and social scientists working closely with fishers and fishery managers.
:::
::::

<br>
<br>

<center>*Future Seas is funded by the NOAA Climate Program Office’s Climate and Fisheries Adaptation (CAFA) program and the NOAA Fisheries Office of Science and Technology.*</center>