---
title: "Predictability of species distributions deteriorates under novel environmental conditions in the California Current System"
date: 2020-07-28
categories: 
  - Species Distribution Modeling and Dynamic Ocean Management
pub-info:
  reference: >-
    Muhling, B. A., Brodie, S., Smith, J. A., Tommasi, D., Gaitan, C. F., Hazen, E. L., Jacox, M. G., Auth, T. D., & Brodeur, R. D. (2020). Predictability of species distributions deteriorates under novel environmental conditions in the California Current System. <em>Frontiers in Marine Science</em>, 7, 589. doi: <a href="https://doi.org/10.3389/fmars.2020.00589">https://doi.org/10.3389/fmars.2020.00589</a>
  links:
    - name: PDF
      url: Muhling_FrontMarSci_2020.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.3389/fmars.2020.00589
      icon: fa-solid fa-scroll
---

## Abstract

Spatial distributions of marine fauna are determined by complex interactions between environmental conditions and animal behaviors. As climate change leads to warmer, more acidic, and less oxygenated oceans, species are shifting away from their historical distribution ranges, and these trends are expected to continue into the future. Correlative Species Distribution Models (SDMs) can be used to project future habitat extent for marine species, with many different statistical methods available. However, it is vital to assess how different statistical methods behave under novel environmental conditions before using these models for management advice, and to consider whether future projections based on these techniques are biologically reasonable. In this study, we built SDMs for adults and larvae of two ecologically important pelagic fishes in the California Current System (CCS): Pacific sardine (*Sardinops sagax*) and northern anchovy (*Engraulis mordax*). We used five different SDM methods, ranging from simple [thermal niche model (TNM)] to complex (artificial neural networks). Our results show that some SDMs trained on data collected between 2003 and 2013 lost substantial predictive skill when applied to observations from more recent years, when ocean temperatures associated with a marine heatwave were outside the range of historical measurements. This decrease in skill was particularly apparent for adult sardine, which showed non-stationary relationships between catch locations and sea surface temperature (SST) through time. While sardine adults and larvae shifted their distributions markedly during the marine heatwave, anchovy largely maintained their historical spatiotemporal distributions. Our results suggest that correlative relationships between species and their environment can become unreliable during anomalous conditions. Understanding the underlying physiology of marine species is therefore essential for the construction of SDMs that are robust to rapidly changing environments. Developing distribution models that offer skillful predictions into the future for species such as sardine and anchovy, which are migratory and include separate sub-stocks, may be particularly challenging.