---
title: "Projecting climate change impacts from physics to fisheries: A view from three California Current fisheries"
date: 2023-02-01
author:
  - name: James Smith
  - name: Mercedes Pozo Buil
  - name: Barbara Muhling
  - name: Desiree Tommasi
  - name: Stephanie Brodie
  - name: Timothy Frawley
  - name: Jerome Fiechter
  - name: Stefan Koenigstein
  - name: Amber Himes-Cornell
  - name: Michael Alexander
  - name: Steven Bograd
  - name: Nathalí Cordero Quirós
  - name: Larry Crowder
  - name: Enrique Curchitser
  - name: Stephanie Green
  - name: Natasha Hardy
  - name: Alan Haynie
  - name: Elliott Hazen
  - name: Kirstin Holsman
  - name: Gwendal Le Fol
  - name: Nerea Lezama-Ochoa
  - name: Ryan Rykaczewski
  - name: Charles Stock
  - name: Stephen Stohs
  - name: Jonathan Sweeney
  - name: Heather Welch
  - name: Michael Jacox
categories: 
  - Climate and Fisheries
pub-info:
  reference: >-
    Smith, J. A., Buil, M. P., Muhling, B., Tommasi, D., Brodie, S., Frawley, T. H., Fiechter, J., Koenigstein, S., Himes-Cornell, A., Alexander, M. A., Bograd, S. J., Quirós, N. C., Crowder, L. B., Curchitser, E., Green, S. J., Hardy, N. A., Haynie, A. C., Hazen, E. L., Holsman, K., Le Fol, G., Lezama-Ochoa, N., Rykaczewski, R. R., Stock, C. A., Stohs, S., Sweeney, J., Welch, H., & Jacox, M. G. (2023). Projecting climate change impacts from physics to fisheries: A view from three California Current fisheries. <em>Progress in Oceanography</em>, 211, 102973. doi: <a href="https://doi.org/10.1016/j.pocean.2023.102973">https://doi.org/10.1016/j.pocean.2023.102973</a>
  links:
    - name: PDF
      url: Smith_PiO_2023.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.1016/j.pocean.2023.102973
      icon: fa-solid fa-scroll
---

## Abstract

Motivated by a need for climate-informed living marine resource management, increased emphasis has been placed on regional end-to-end modeling frameworks designed to project climate impacts on marine ecosystems and evaluate the efficacy of potential management strategies under changing conditions. The ‘Future Seas’ project was initiated with a focus on three fisheries (Pacific sardine, swordfish, and albacore tuna) in the California Current System (CCS). This work leverages a suite of climate, ocean, ecosystem, and economic models to project physical, ecological, and socio-economic change, evaluate management strategies, and quantify uncertainty in model projections. Here we describe the components of the modeling framework, considerations underlying choices made in model development, engagement with stakeholders, and key physical, ecological, and socio-economic results to date, including projections to 2100. Our broad aims are to (i) synthesize a large body of climate and fisheries research that has been conducted, and continues, under the Future Seas umbrella, and (ii) provide insight and recommendations to those pursuing similar efforts for other applications and in other regions. In general, our results indicate that all three species will likely shift their distributions (predominantly poleward) in the future, which impacts accessibility to fishing fleets, spatial management, and quota allocation. For similar integrative climate-to-fisheries projections, we recommend attention is given to: recognizing potential biases arising from differences between the climate products used for ecological model fitting and those used for model projection; how sources of projection uncertainty are prioritized, incorporated, and communicated; and quantitatively linking scenarios – especially socio-economic scenarios – with climate and ecological projections.