---
title: "Exploring timescales of predictability in species distributions"
date: 2021-03-16
categories: 
  - Species Distribution Modeling and Dynamic Ocean Management
pub-info:
  reference: >-
    Brodie, S., Abrahms, B., Bograd, S. J., Carroll, G., Hazen, E. L., Muhling, B. A., Pozo Buil, M., Smith, J. A., Welch, H., & Jacox, M. G. (2021). Exploring timescales of predictability in species distributions. <em>Ecography</em>, 44(6), 832-844. doi: <a href="https://doi.org/10.1111/ecog.05504">https://doi.org/10.1111/ecog.05504</a>
  links:
    - name: PDF
      url: Brodie_Ecography_2021.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.1111/ecog.05504
      icon: fa-solid fa-scroll
---

## Abstract

Accurate forecasts of how animals respond to climate-driven environmental change are needed to prepare for future redistributions, however, it is unclear which temporal scales of environmental variability give rise to predictability of species distributions. We examined the temporal scales of environmental variability that best predicted spatial abundance of a marine predator, swordfish *Xiphias gladius*, in the California Current. To understand which temporal scales of environmental variability provide biological predictability, we decomposed physical variables into three components: a monthly climatology (long-term average), a low frequency component representing interannual variability, and a high frequency (sub-annual) component that captures ephemeral features. We then assessed each component's contribution to predictive skill for spatially-explicit swordfish catch. The monthly climatology was the primary source of predictability in swordfish spatial catch, reflecting the spatial distribution associated with seasonal movements in this region. Importantly, we found that the low frequency component (capturing interannual variability) provided significant skill in predicting anomalous swordfish distribution and catch, which the monthly climatology cannot. The addition of the high frequency component added only minor improvement in predictability. By examining models' ability to predict species distribution anomalies, we assess the models in a way that is consistent with the goal of distribution forecasts – to predict deviations of species distributions from their average historical locations. The critical importance of low frequency climate variability in describing anomalous swordfish distributions and catch matches the target timescales of physical climate forecasts, suggesting potential for skillful ecological forecasts of swordfish distributions across short (seasonal) and long (climate) timescales. Understanding sources of prediction skill for species environmental responses gives confidence in our ability to accurately predict species distributions and abundance, and to know which responses are likely less predictable, under future climate change. This is important as climate change continues to cause an unprecedented redistribution of life on Earth.