---
title: "Ocean and Climate Modeling"
toc: false
---

![Spatial domains of the ROMS-NEP downscaled physics projections (blue), the
CCLME Atlantis domain (orange), and the ROMS-CCLME downscaled physics and
biogeochemistry (green).](images/Fig_ClimateModeling.jpg){#fig-clim-mod fig-align="center" width=75%}

The ocean and climate modeling team is developing high-resolution, downscaled projections of
future conditions in the California Current System and Gulf of Alaska. We use physical and
biogeochemical conditions from an ensemble of high-resolution (~0.1°) projections for the
California Current Large Marine Ecosystem (CCLME) forced by three earth system models
(ESMs) belonging to the CMIP6 archive under the “middle of the road” shared-socio-economic
pathway (SSP2-4.5): GFDL-ESM4, IPSL-CM6A-LR, UKESM1-0-LL. Output from these ESMs
provide the surface and ocean boundary conditions for an implementation of the Regional Ocean
Modeling System (ROMS) coupled with a biogeochemical model, the North Pacific Ecosystem
Model for Understanding Regional Oceanography (NEMURO). Prior to downscaling, the output
from the ESMs is bias corrected using a time-varying delta approach that includes the daily
variability in the atmospheric forcing and the monthly variability in the ocean boundary
conditions, following Pozo Buil et al. (2021). The regional modeling strategy includes two
domains (@fig-clim-mod). The first domain includes the northeast Pacific (ROMS-NEP), extending
from Baja California to the Gulf of Alaska. In this domain only the physical ocean circulation is
resolved. This broader northeastern Pacific region is essential for capturing migratory patterns of
shared, transboundary stocks in the CPS, HMS, and groundfish Fishery Management Plans. The
second domain covers the Atlantis domain from Baja California to British Columbia (ROMS-
CCLME), and the solution will include both ocean physics and biogeochemistry.


## References
Pozo Buil, M., Jacox, M. G., Fiechter, J., Alexander, M. A., Bograd, S. J., Curchitser, E. N., ... &
Stock, C. A. (2021). A dynamically downscaled ensemble of future projections for the California
current system. *Frontiers in Marine Science*, 8, 612874.
<https://doi.org/10.3389/fmars.2021.612874>