---
title: "Impacts to Fishing Communities"
toc: false
---

![Participation networks for each CPS fleet segment for 2005-2014. CPS-associated
metiers are shown in blue with their labels bolded; everything else is shown in beige. Nodes
represent fishing metiers, and their size represents their percentage contribution to total revenue
generated by each fleet segment during each time period. The width of the lines connecting the
nodes represents the percentage of vessels in each fleet segment participating in each pair of
fisheries. See Quezada et al. 2023 for a detailed description of each fleet segment.](images/Fig_FishingCommunities1.jpg){#fig-fish-comm1 fig-align="center" width=75%}

<br>
The Future Seas social science and economics teams are working to understand how projected
changes in species distribution and abundance will impact the future resilience of fishing
communities.

Quezada et al. (2023) investigated historical landings per vessel of coastal pelagic species (CPS,
here sardine, anchovy, market squid) in response to shifts in their availability, to understand how
the fleet may respond to future changes. Shifts in availability were derived from
environmentally-driven [SDM output](Species_Distribution_Modeling.qmd) averaged over fishing grounds. They
found that responses to historical shifts in species availability were dependent on fleet segment
and associated vessel strategies (e.g., opportunist versus specialist fleets, see @fig-fish-comm1 for
overview of fleet segments), in addition to market conditions, regulations, and availability of
other target species. This work also highlighted that existing characteristics of some fleet
segments, such as the ability to switch between a diverse set of target species, can confer future
adaptation potential. See Quezada et al. 2023 to learn more! The code used for the analysis is
available at <https://github.com/futureseas/EconAnalysis>.

<br>

![Commercial fishing reliance index scores by fishery management group compared
against social vulnerability measures for West Coast ports in 2020. The commercial fishing
index is based on fishery landings, revenues, permits, and processing variables on a per capita
basis. Color scale shows generalized socioeconomic vulnerability of coastal communities, which
considers census demographics, personal disruption, poverty, housing characteristics, housing
disruption, and labor force structure, positive values indicate greater vulnerability (Jepson &amp;
Colburn 2013).](images/Fig_FishingCommunities2.jpg){#fig-fish-comm2 fig-align="center" width=75%}

<br>
The Future Seas team focused on communities will leverage existing methods for assessing the
climate vulnerability of fishing communities within a social-ecological framework (Colburn et
al. 2016; @fig-fish-comm2), including those specific to West Coast fisheries (Koehn et al. 2022; Norman
et al. 2022; Frawley et al. 2021), and explore the applicability of these measures to individual
commercial harvesters. This will be accomplished by pairing community level measures with
data from a longitudinal West Coast fishery participation survey (Holland et al. 2019; Norman et
al. 2022). These data will enable examination of how secondary vulnerability measures are
related to individual harvester responses to exogenous shocks, including closures and other
management interventions. The pairing of these data with climate-oriented community measures
(Koehn et al. 2022) allows for further exploration of varying adaptive capacities, at the level of
the individual, fleet and aggregated IO-PAC port.

Climate social-ecological vulnerability measures will also be compared with regional climate
risk perceptions by building upon the PFMC Climate and Communities Initiative scenarios and
considering how place-based vulnerability relates to regional perceptions about future challenges
and mitigation strategies. Regional perceptions will also be compared across fleet and IO-PAC
port level scales while considering their collective vulnerability to climate change. Finally, these
perceptions will be compared with the future projections of ecosystem states and management
responses produced by Atlantis. Insights gained through this process can potentially serve to
inform future stakeholder engagement for enhancing climate resilience of fishing communities.


## References
Colburn, L. Jepson, M., Weng, C., Seara, T., Weiss, J., & Hare, J. A. 2016. Indicators of climate
change and social vulnerability in fishing dependent communities along the Eastern and Gulf
Coasts of the United States. *Marine Policy*, 74, 323–333.

Frawley T.H., Muhling B.A., Brodie S., Fisher M.C., Tommasi D., Le Fol G., et al. 2021.
Changes to the structure and function of an albacore fishery reveal shifting social-ecological
realities for Pacific Northwest fishermen. *Fish and Fisheries*. 22(2): 280–297.

Holland D., Abbott J, Norman K. 2020. Fishing to live or living to fish: job satisfaction and
identity of west coast fishermen. *Ambio*, 49: 628–639. doi:10.1007/s13280-019-01206-w

Jepson, M. & Colburn, L. 2013. Development of Social Indicators of Fishing Community
Vulnerability and Resilience in the US Southeast and Northeast Regions, *NOAA Technical Memorandum* NMFS-F/SPO-129

Koehn LE, Nelson LK, Samhouri JF, Norman KC, Jacox MG, et al. 2022. Social-
ecological vulnerability of fishing communities to climate change: A US West Coast case study.
*PloS One*, 17: e0272120.

Norman, K., Holland, D., Abbott, & Phillips, A. 2022. Community-level fishery measures and
individual Fishers: comparing primary and secondary data for the U.S. West Coast. *Ocean and Coastal Management*, 224: 106191, doi:10.1016/j.ocecoaman.2022.106191

Quezada, F. J., Tommasi, D., Frawley, T. H., Muhling, B., Kaplan, I., & Stohs, S. (2023). Catch
as catch can: Markets, availability, and fishery closures drive distinct responses among the US
West Coast Coastal Pelagic Species fleet segments. *Canadian Journal of Fisheries and Aquatic Sciences*. 81(8): 1135-1153.