---
title: "Projected Shifts in 21st Century Sardine Distribution and Catch in the California Current"
date: 2021-07-18
categories: 
  - Climate and Fisheries
  - Species Distribution Modeling and Dynamic Ocean Management
pub-info:
  reference: >-
    Fiechter, J., Pozo Buil, M., Jacox, M. G., Alexander, M. A., & Rose, K. A. (2021). Projected Shifts in 21st Century Sardine Distribution and Catch in the California Current. <em>Frontiers in Marine Science</em>, 8, 685241. doi: <a href="https://doi.org/10.3389/fmars.2021.685241">https://doi.org/10.3389/fmars.2021.685241</a> 
  links:
    - name: PDF
      url: Fiechter_FrontMarSci_2021.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Online
      url: https://doi.org/10.3389/fmars.2021.685241
      icon: fa-solid fa-scroll
---

## Abstract

Predicting changes in the abundance and distribution of small pelagic fish species in response to anthropogenic climate forcing is of paramount importance due to the ecological and socioeconomic importance of these species, especially in eastern boundary current upwelling regions. Coastal upwelling systems are notorious for the wide range of spatial (from local to basin) and temporal (from days to decades) scales influencing their physical and biogeochemical environments and, thus, forage fish habitat. Bridging those scales can be achieved by using high-resolution regional models that integrate global climate forcing downscaled from coarser resolution earth system models. Here, “end-to-end” projections for 21st century sardine population dynamics and catch in the California Current system (CCS) are generated by coupling three dynamically downscaled earth system model solutions to an individual-based fish model and an agent-based fishing fleet model. Simulated sardine population biomass during 2000–2100 exhibits primarily low-frequency (decadal) variability, and a progressive poleward shift driven by thermal habitat preference. The magnitude of poleward displacement varies noticeably under lower and higher warming conditions (500 and 800 km, respectively). Following the redistribution of the sardine population, catch is projected to increase by 50–70% in the northern CCS and decrease by 30–70% in the southern and central CCS. However, the late-century increase in sardine abundance (and hence, catch) in the northern CCS exhibits a large ensemble spread and is not statistically identical across the three downscaled projections. Overall, the results illustrate the benefit of using dynamical downscaling from multiple earth system models as input to high-resolution regional end-to-end (“physics to fish”) models for projecting population responses of higher trophic organisms to global climate change.